# POST http://127.0.0.1:5000/client/sync HTTP/1.1
# Content-Type: application/json

# {
#     "token": "H3SGRL763777WFK5DXOI4OGU4XQDZ4VB",
#     "otp": "350835",
#     "clients": [
#         {
#             "id": "23423532534",
#             "email": "abc@t333.com"
#         }
#     ]
    
# }

# POST http://127.0.0.1:8593/test HTTP/1.1
# Content-Type: application/json

# {
#     "access_key": "hfmvnauvjz7duyupmxrbu2c737s3x4x9",
#     "secret_key": "fmmztmgw3xriue3aj5goczc25dxnfyy9"
# }

POST http://127.0.0.1:8593/client/sync HTTP/1.1
Content-Type: application/json

{
    "access_key": "hfmvnauvjz7duyupmxrbu2c737s3x4x9",
    "secret_key": "fmmztmgw3xriue3aj5goczc25dxnfyy9",
    "clients": [
         {
             "id": "23423532534",
             "email": "abc@t333.com"
         }
     ]
}