spring:
  profiles:
    active: dev
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
  mail:
    host:
    username:
    password:
  jpa:
    database: mariadb

mybatis:
  type-aliases-package: cc.larryzeta.manager.entity
  mapper-locations: classpath:mapper/*.xml

flask:
  base:
    url:
      list:
        https://node1/api, https://node2/api

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/xray
    username: root
    password: ROOT
  thymeleaf:
    cache: false

xray:
  config-file: /config.json

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/xray
    username: root
    password:
server:
  address: 127.0.0.1

xray:
  config-file: /usr/local/etc/xray/config.json

