spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/xray
    username:
    password:
  mail:
    host:
    username:
    password:
  jpa:
    database: mariadb

mybatis:
  type-aliases-package: cc.larryzeta.manager.entity
  mapper-locations: classpath:mapper/*.xml

shim:
  access-key: hfmvnauvjz7duyupmxrbu2c737s3x4x9
  secret-key: fmmztmgw3xriue3aj5goczc25dxnfyy9

server:
  address: 127.0.0.1
