spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/xray
    username:
    password:
  mail:
    host:
    username:
    password:
  jpa:
    database: mariadb

mybatis:
  type-aliases-package: cc.larryzeta.manager.entity
  mapper-locations: classpath:mapper/*.xml

server:
  address: 127.0.0.1

jwt:
  secret:
  timeout: 1800000
