spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/xray
    username:
    password: 
    hikari:
      autoCommit: true
      connectionTimeOut: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 10
      minimumIdle: 10
      poolName: hikari
      registerMbeans: true

  mail:
    host:
    username:
    password:
  jpa:
    database: mariadb

mybatis:
  type-aliases-package: cc.larryzeta.manager.entity
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: jLThtAoDUA2ZLVRWJy3FnsTfp2vUpNjR
  timeout: 1800000