spring:
  profiles:
    active: @activatedProperties@
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
  mail:
    host:
    username:
    password:
  jpa:
    database: mariadb

mybatis:
  type-aliases-package: cc.larryzeta.manager.entity
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret:
  timeout: 1800000

---


